// Package sshconf parses OpenSSH client config files well enough to import
// existing Host blocks into sshm.
//
// This is intentionally a reader, never a writer: sshm keeps its own store as
// the source of truth and never rewrites ~/.ssh/config, because that file is
// often hand-maintained, shared, or generated by other tools.
package sshconf

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/sohail/sshm/internal/model"
)

// DefaultPath returns ~/.ssh/config.
func DefaultPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "config"
	}
	return filepath.Join(home, ".ssh", "config")
}

// maxIncludeDepth guards against Include cycles, which ssh itself also refuses
// to follow indefinitely.
const maxIncludeDepth = 8

// ParseFile reads path and any files it Includes, returning importable hosts in
// file order plus human-readable warnings about entries that were skipped.
//
// A real ~/.ssh/config accumulates odd entries over the years. Anything that
// would not produce a usable connection is dropped and reported rather than
// imported, so the host list never contains an entry that cannot be dialled.
func ParseFile(path string) ([]model.Host, []string, error) {
	return parseFile(path, 0, map[string]bool{})
}

func parseFile(path string, depth int, seen map[string]bool) ([]model.Host, []string, error) {
	if depth > maxIncludeDepth {
		return nil, nil, fmt.Errorf("ssh config include depth exceeded at %s", path)
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		abs = path
	}
	if seen[abs] {
		return nil, nil, nil // already visited; skip the cycle
	}
	seen[abs] = true

	f, err := os.Open(path)
	if err != nil {
		return nil, nil, err
	}
	defer f.Close()

	return parse(f, filepath.Dir(abs), depth, seen)
}

// Parse reads an ssh config from r. baseDir resolves relative Include paths.
// It returns importable hosts and warnings about entries that were skipped.
func Parse(r io.Reader, baseDir string) ([]model.Host, []string, error) {
	return parse(r, baseDir, 0, map[string]bool{})
}

func parse(r io.Reader, baseDir string, depth int, seen map[string]bool) ([]model.Host, []string, error) {
	var (
		out      []model.Host
		warnings []string
		current  []*model.Host // a single Host line may declare several patterns
		inMatch  bool          // Match blocks are conditional; we skip their bodies
		blockAt  int           // line number the current Host block started on
	)

	flush := func() {
		for _, h := range current {
			if h.Hostname == "" {
				// "Host web" with no HostName means ssh connects to "web".
				h.Hostname = h.Alias
			}
			h.Normalize()
			if err := h.Validate(); err != nil {
				warnings = append(warnings, fmt.Sprintf("line %d: skipped: %v", blockAt, err))
				continue
			}
			out = append(out, *h)
		}
		current = nil
	}

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		key, val, ok := splitLine(sc.Text())
		if !ok {
			continue
		}

		switch strings.ToLower(key) {
		case "host":
			flush()
			inMatch = false
			blockAt = lineNo
			for _, pat := range splitFields(val) {
				if !importablePattern(pat) {
					continue
				}
				current = append(current, &model.Host{Alias: pat, Source: "ssh_config"})
			}

		case "match":
			// Everything until the next Host block is conditional. Importing it
			// unconditionally would produce wrong connection settings.
			flush()
			inMatch = true

		case "include":
			if inMatch {
				continue
			}
			// Close any open block first: directives after the Include belong
			// to whatever the included file leaves open, which we do not model.
			flush()
			for _, pat := range splitFields(val) {
				for _, inc := range expandInclude(pat, baseDir) {
					hosts, warns, err := parseFile(inc, depth+1, seen)
					if err != nil {
						warnings = append(warnings,
							fmt.Sprintf("could not read included file %s: %v", inc, err))
						continue // an unreadable include is not fatal
					}
					out = append(out, hosts...)
					warnings = append(warnings, warns...)
				}
			}

		default:
			if inMatch || len(current) == 0 {
				continue
			}
			for _, h := range current {
				applyKeyword(h, key, val)
			}
		}
	}
	flush()
	if err := sc.Err(); err != nil {
		return out, warnings, err
	}
	return out, warnings, nil
}

func applyKeyword(h *model.Host, key, val string) {
	switch strings.ToLower(key) {
	case "hostname":
		h.Hostname = val
	case "user":
		h.User = val
	case "port":
		if n, err := strconv.Atoi(val); err == nil && n > 0 && n < 65536 {
			h.Port = n
		}
	case "identityfile":
		if h.IdentityFile == "" { // ssh uses the first match; so do we
			h.IdentityFile = val
		}
	case "proxyjump":
		h.ProxyJump = val
	case "hostkeyalias", "identitiesonly", "serveraliveinterval", "serveralivecountmax",
		"forwardagent", "compression", "stricthostkeychecking", "userknownhostsfile",
		"preferredauthentications", "pubkeyauthentication", "connecttimeout",
		"requesttty", "addkeystoagent", "controlmaster", "controlpath", "controlpersist":
		// Carry through the directives that actually change how a session
		// behaves, as -o options.
		h.Options = append(h.Options, canonicalKeyword(key)+"="+val)
	default:
		// Everything else (LocalForward, SendEnv, ...) is left behind on
		// purpose: importing it blindly produces surprising sessions. The
		// original ~/.ssh/config still applies to plain `ssh`.
	}
}

// canonicalKeyword restores OpenSSH's CamelCase spelling for known keywords so
// that generated -o flags read naturally.
func canonicalKeyword(key string) string {
	known := []string{
		"HostKeyAlias", "IdentitiesOnly", "ServerAliveInterval", "ServerAliveCountMax",
		"ForwardAgent", "Compression", "StrictHostKeyChecking", "UserKnownHostsFile",
		"PreferredAuthentications", "PubkeyAuthentication", "ConnectTimeout",
		"RequestTTY", "AddKeysToAgent", "ControlMaster", "ControlPath", "ControlPersist",
	}
	lower := strings.ToLower(key)
	for _, k := range known {
		if strings.ToLower(k) == lower {
			return k
		}
	}
	return key
}

// importablePattern rejects wildcard and negated patterns. "Host *" is a
// defaults block, not a server, and importing it would create a bogus entry.
func importablePattern(pat string) bool {
	if pat == "" {
		return false
	}
	if strings.ContainsAny(pat, "*?!") {
		return false
	}
	return true
}

func expandInclude(pat, baseDir string) []string {
	pat = expandTilde(pat)
	if !filepath.IsAbs(pat) {
		pat = filepath.Join(baseDir, pat)
	}
	matches, err := filepath.Glob(pat)
	if err != nil || len(matches) == 0 {
		return nil
	}
	return matches
}

func expandTilde(p string) string {
	if p == "" || p[0] != '~' {
		return p
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return p
	}
	if len(p) == 1 {
		return home
	}
	if p[1] == '/' {
		return filepath.Join(home, p[1:])
	}
	return p
}

// splitLine splits "Key value", "Key=value" and "Key = value", strips comments
// and returns ok=false for blank or comment-only lines.
func splitLine(line string) (key, val string, ok bool) {
	line = strings.TrimSpace(line)
	if line == "" || strings.HasPrefix(line, "#") {
		return "", "", false
	}
	i := strings.IndexAny(line, " \t=")
	if i < 0 {
		return "", "", false
	}
	key = line[:i]
	val = strings.TrimSpace(line[i:])
	val = strings.TrimSpace(strings.TrimPrefix(val, "="))
	if val == "" {
		return "", "", false
	}
	return key, unquote(val), true
}

// splitFields splits a value on whitespace while respecting double quotes,
// which ssh allows around patterns and paths containing spaces.
func splitFields(s string) []string {
	var (
		out   []string
		cur   strings.Builder
		inQ   bool
		flush = func() {}
	)
	flush = func() {
		if cur.Len() > 0 {
			out = append(out, cur.String())
			cur.Reset()
		}
	}
	for _, r := range s {
		switch {
		case r == '"':
			inQ = !inQ
		case (r == ' ' || r == '\t') && !inQ:
			flush()
		default:
			cur.WriteRune(r)
		}
	}
	flush()
	return out
}

func unquote(s string) string {
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

// Dedup merges imported hosts against existing ones. Hosts whose alias already
// exists are returned in `skipped` rather than overwriting local edits.
func Dedup(existing []model.Host, imported []model.Host) (added, skipped []model.Host) {
	have := make(map[string]struct{}, len(existing))
	for _, h := range existing {
		have[strings.ToLower(h.Alias)] = struct{}{}
	}
	for _, h := range imported {
		k := strings.ToLower(h.Alias)
		if _, dup := have[k]; dup {
			skipped = append(skipped, h)
			continue
		}
		have[k] = struct{}{}
		added = append(added, h)
	}
	return added, skipped
}
